import Head from 'next/head'
import Image from 'next/image'
import Loader from '../components/Loader'
import toast from 'react-hot-toast';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='pt-20'>
        <Loader show />
        <button onClick={() => toast.success('hello toast!')}>
          Toast Me
        </button>
      </main>


    </div>
  )
}
